---
blank_issues_enabled: true
contact_links:
  - name: NetasCode ISE Site
    url: https://netascode.cisco.com/solutions/ise/overview
    about: Please review additional information on the NetasCode site.
